### ISSUE TITLE
Wrong values in SORT BY lead to error status 500

### ISSUE THREAD

**Issue by hoelger-frachtwerk** [Frachtwerk/essencium-backend#390]
**Describe the bug**
From a child project I have the error `org.springframework.data.mapping.PropertyReferenceException: No property '<string>' found for type 'Zone' in "findAllZones"` because SORT BY expects the arguments column and order (`cathegory|partner|hub, desc|asc`). 

**To Reproduce**
TODO

**Expected behavior**
When unexpected values are received, this should be a "bad request" with error status 400 and a more verbose error message, so the user directly knows what to improve.

**Additional context**
A solution is probably to be implemented in `de.frachtwerk.essencium.backend.controller.adviceRestExceptionHandler` and with 

code snippet from my notes:
```
@ExceptionHandler(PropertyReferenceException.class)
protected ResponseEntity<Object> handlePropertyReferenceException(
  PropertyReferenceException ex, WebRequest request) {
    return new ResponseEntity<>();
}
```

**Comment by hoelger-frachtwerk** [comment]
```
org.springframework.data.mapping.PropertyReferenceException: No property '<string>' found for type 'Zone'
        ...
	at de.frachtwerk.essencium.backend.service.AbstractCrudService.getAllFiltered(AbstractCrudService.java:110) ~[essencium-backend-2.5.12.jar:2.5.12]
	at de.frachtwerk.essencium.backend.controller.AbstractAccessAwareController.findAll(AbstractAccessAwareController.java:137) ~[essencium-backend-2.5.12.jar:2.5.12]
	at de.frachtwerk.oslpartnerportal.controller.ZoneController.findAll(ZoneController.java:57) ~[classes/:na]
```
These are the only stack trace lines from our code, this is so confusing, why can't the line of code which is trying to convert this string to some enum-like be directly referenced?! arghmpf :D
